# Title: Basic ARM Assembly WEEK 5 Assign
# Purpose: Week 5 Makefile
# Author: Justin E
# Edit Date: 01MAR2021
# JHU - COMP ORG - EN.605.204.8VL.SP21 Computer Organization

all: c2fprogram f2cprogram ftintoinches inctofeetandinches prog6_multiplyten TwosComp

c2fprogram: c2fprogram.s
	gcc $@.s -g -o $@ 

f2cprogram: f2cprogram.s
	gcc $@.s -g -o $@

ftintoinches: ftintoinches.s
	gcc $@.s -g -o $@

inctofeetandinches: inctofeetandinches.s
	gcc $@.s -g -o $@

prog6_multiplyten: prog6_multiplyten.s
	gcc $@.s -g -o $@

TwosComp: TwosComp.s
	gcc $@.s -g -o $@
