all: AddSubtract Multiply Divide OtherMultiply ChangeCase EorExample MovExample ShiftExample

AddSubtract: AddSubtract.s
	gcc $@.s -g -o $@ 

Multiply: Multiply.s
	gcc $@.s -g -o $@

OtherMultiply: OtherMultiply.s
	gcc $@.s -g -o $@

Divide: Divide.s
	gcc $@.s -g -o $@

ChangeCase: ChangeCase.s
	gcc $@.s -g -o $@

EorExample: EorExample.s
	gcc $@.s -g -o $@

MovExample: MovExample.s
	gcc $@.s -g -o $@

ShiftExample: ShiftExample.s
	gcc $@.s -g -o $@

