
All: Template IOExample_1 IOExample_2 IOExample_3 IOExample_4

Template: Template.s
	gcc $@.s -g -o $@

IOExample_1: IOExample_1.s
	gcc $@.s -g -o $@

IOExample_2: IOExample_2.s
	gcc $@.s -g -o $@

IOExample_3: IOExample_3.s
	gcc $@.s -g -o $@

IOExample_4: IOExample_4.s
	gcc $@.s -g -o $@
