all: Spaghetti Logical CheckGrade PrintGrade

Spaghetti: Spaghetti.s
	gcc $@.s -g -o $@

Logical: Logical.s
	gcc $@.s -g -o $@

CheckGrade: CheckGrade.s
	gcc $@.s -g -o $@

PrintGrade: PrintGrade.s
	gcc $@.s -g -o $@
